spring:
  datasource:
    url: jdbc:mysql://localhost:3307/provider?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  